siteconv/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("converter/", include("converter.urls", namespace="converter")),
    path("", RedirectView.as_view(url="/converter/", permanent=False), name="home"),
    path("api/converter/", include("converter.api.urls", namespace="converter_api")),
    path("users/", include("users.urls", namespace="users")),
    path("api-key/", include("users.api.urls", namespace="api_key")),
]

users/api/urls.py
from django.urls import path
from .views import APIKeyView, APIKeyRefreshView


app_name = "api_key"

urlpatterns = [
    path("get-api-key/", APIKeyView.as_view(), name="get_or_create_api_key"),
    path("refresh-api-key/", APIKeyRefreshView.as_view(), name="refresh_api_key"),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users import views
from .forms import EmailOrUsernameAuthenticationForm

app_name = "users"

urlpatterns = [
    path("register/", views.RegisterUserView.as_view(), name="register"),
    path(
        "login/",
        LoginView.as_view(
            template_name="users/login.html",
            authentication_form=EmailOrUsernameAuthenticationForm,
        ),
        name="login",
    ),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from .api.utils import generate_api_key


class UserAPIKey(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="api_key")
    key = models.CharField(max_length=48, unique=True, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def regenerate_key(self):
        self.key = generate_api_key()
        self.save()

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class EmailOrUsernameAuthenticationForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "Username or email"

    def clean(self):
        username_or_email = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")

        if username_or_email and password:
            self.user_cache = authenticate(
                self.request, username=username_or_email, password=password
            )
            if self.user_cache is None:
                raise forms.ValidationError("Invalid password or username/email")
        return self.cleaned_data

users/api/views.py
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated
from ..models import UserAPIKey
from rest_framework import status


class APIKeyView(APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request):
        api_key_obj, created = UserAPIKey.objects.get_or_create(user=request.user)

        if created or not api_key_obj.key:
            api_key_obj.regenerate_key()

        return Response({"api_key": api_key_obj.key}, status=status.HTTP_200_OK)


class APIKeyRefreshView(APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request):
        try:
            api_key_obj = request.user.api_key
        except UserAPIKey.DoesNotExist:
            return Response(
                {"result": "API-key not found"}, status=status.HTTP_404_NOT_FOUND
            )

        api_key_obj.regenerate_key()
        return Response({"api_key": api_key_obj.key}, status=status.HTTP_200_OK)

users/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import FormView
from django.contrib.auth import login
from .forms import CustomUserCreationForm
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


class RegisterUserView(FormView):
    form_class = CustomUserCreationForm
    template_name = "users/register.html"
    success_url = reverse_lazy("profile")

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return super().form_valid(form)


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = "users/profile.html"

users/templates/users/login.html
{% extends "converter/base.html" %}
{% load static %}

{% block title %}Login{% endblock %}

{% block content %}
  <link rel="stylesheet" href="{% static 'users/css/styles.css' %}">
    <h3 class="convert-heading">Login to your account</h3>

  <form method="post">
    {% csrf_token %}

    {% for field in form %}
      {{ field.label_tag }}
      {{ field }}
      {% if field.errors %}
        <ul class="errorlist">
          {% for error in field.errors %}
            <li>{{ error }}</li>
          {% endfor %}
        </ul>
      {% endif %}
    {% endfor %}

    {% if form.non_field_errors %}
      <ul class="errorlist">
        {% for error in form.non_field_errors %}
          <li>{{ error }}</li>
        {% endfor %}
      </ul>
    {% endif %}

    <div class="button-wrapper">
        <button type="submit" class="convert-button">Login</button>
    </div>
</form>

<div class="down-wrapper">
    <a href="{% url 'users:register' %}" class="link">Don't have an account? Register here</a>
</div>

{% endblock %}

users/templates/users/profile.html
{% extends "converter/base.html" %}
{% load static %}

{% block title %}Profile{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'users/css/styles.css' %}">

<h3 class="convert-heading">Welcome, {{ user.username }}!😎</h3>

<p class="profile-subtext">This is your profile page👤✅</p>

<div id="api-key-section" class="button-wrapper">
    <button id="get-key-btn" class="convert-button">Get API key🛠️</button>
    <button id="refresh-key-btn" style="display: none;" class="convert-button">Refresh API key</button>
    <p id="api-key-display"></p>
</div>

<script>
    const getOrCreateAPIKey = "{% url 'api_key:get_or_create_api_key' %}";
    const refreshAPIKey = "{% url 'api_key:refresh_api_key' %}";
</script> 
<script src='{% static "users/js/api-key.js" %}'></script>

<div class="logout-wrapper">
    To logout click <a href="{% url 'users:logout' %}" class="link">Here</a></p>
</div>


{% endblock %}

users/templates/users/register.html
{% extends "converter/base.html" %}
{% load static %}

{% block title %}Register{% endblock %}

{% block content %}
  <link rel="stylesheet" href="{% static 'users/css/styles.css' %}">
    <h3 class="convert-heading">Registration</h3>

  <form method="post">
    {% csrf_token %}

    {% for field in form %}
      {{ field.label_tag }}
      {{ field }}
      {% if field.errors %}
        <ul class="errorlist">
          {% for error in field.errors %}
            <li>{{ error }}</li>
          {% endfor %}
        </ul>
      {% endif %}
    {% endfor %}

    {% if form.non_field_errors %}
      <ul class="errorlist">
        {% for error in form.non_field_errors %}
          <li>{{ error }}</li>
        {% endfor %}
      </ul>
    {% endif %}

    <div class="button-wrapper">
        <button type="submit" class="convert-button">Register</button>
    </div>
</form>

{% endblock %}