converter/api/urls.py
from django.urls import path
from .views import AsyncConvertView, ResultsConvertView


app_name = "converter_api"

urlpatterns = [
    path("convert/", AsyncConvertView.as_view(), name="convert"),
    path("result/<str:token>/", ResultsConvertView.as_view(), name="result"),
]

converter/urls.py
from django.urls import path
from . import views


app_name = "converter"

urlpatterns = [
    path(
        "get-target-formats/",
        views.GetTargetFormatView.as_view(),
        name="get_target_formats",
    ),
    path("", views.SelectFileView.as_view(), name="select_file"),
    path(
        "select-format/for/<slug:category>/",
        views.SelectFormatView.as_view(),
        name="select_format",
    ),
    path(
        "convert/<slug:input_format>/to/<slug:output_format>/",
        views.ConvertView.as_view(),
        name="convert",
    ),
    path(
        "convert-progress-info/<str:token>/",
        views.ProgressbarView.as_view(),
        name="convert_progress_info",
    ),
    path(
        "convert-progress/<str:token>/",
        views.ConvertProgressView.as_view(),
        name="convert_progress",
    ),
    path(
        "download-file/<str:token>/",
        views.DownloadFileView.as_view(),
        name="download_file",
    ),
]

siteconv/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("converter/", include("converter.urls", namespace="converter")),
    path("", RedirectView.as_view(url="/converter/", permanent=False), name="home"),
    path("api/converter/", include("converter.api.urls", namespace="converter_api")),
    path("users/", include("users.urls", namespace="users")),
    path("api-key/", include("users.api.urls", namespace="api_key")),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users import views
from .forms import EmailOrUsernameAuthenticationForm

app_name = "users"

urlpatterns = [
    path("register/", views.RegisterUserView.as_view(), name="register"),
    path(
        "login/",
        LoginView.as_view(
            template_name="users/login.html",
            authentication_form=EmailOrUsernameAuthenticationForm,
        ),
        name="login",
    ),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

converter/models.py
from django.db import models


class FormatType(models.TextChoices):
    IMAGE = "image", "Image"
    DOCUMENT = "document", "Document"
    AUDIO = "audio", "Audio"
    VIDEO = "video", "Video"


class FileFormat(models.Model):
    name = models.CharField(max_length=10, unique=True)
    file_type = models.CharField(max_length=10, choices=FormatType.choices)

    def __str__(self):
        return f"{self.name} ({self.file_type})"


class FormatConversion(models.Model):
    input_format = models.ForeignKey(
        FileFormat, related_name="conversions_from", on_delete=models.CASCADE
    )
    output_format = models.ForeignKey(
        FileFormat, related_name="conversions_to", on_delete=models.CASCADE
    )
    video_codec = models.CharField(max_length=50, blank=True, null=True)
    audio_video_codec = models.CharField(max_length=50, blank=True, null=True)
    audio_codec = models.CharField(max_length=50, blank=True, null=True)
    engine = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return f"{self.input_format.name} → {self.output_format.name}"


class ConverterMap(models.Model):
    format_type = models.CharField(
        max_length=10, choices=FormatType.choices, unique=True
    )
    class_path = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.format_type}: {self.class_path}"

converter/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.conf import settings


class ConvertForm(forms.Form):
    input_format = forms.ChoiceField()
    output_format = forms.ChoiceField()


class FileForm(forms.Form):
    file = forms.FileField()

    def clean_file(self):
        file = self.cleaned_data.get("file")
        max_size = settings.MAX_FORM_FILE_SIZE

        if file and file.size > max_size:
            raise ValidationError(f"Max file size is {max_size / (1024 ** 3):.1f} GB")
        return file

converter/api/views.py
import os
from django.http import FileResponse
from rest_framework.views import APIView
from rest_framework.parsers import MultiPartParser, FormParser
from ..tasks import convert_task
import secrets
from rest_framework.response import Response
from django.conf import settings
import mimetypes
from ..utils.redis_ext_client import redis_client
from rest_framework.permissions import IsAuthenticated


class AsyncConvertView(APIView):
    parser_classes = [MultiPartParser, FormParser]
    permission_classes = [IsAuthenticated]

    def post(self, request):
        file = request.FILES.get("file")
        output_format = request.data.get("output_format")

        if not file:
            return Response({"error": "No uploaded file found"}, status=400)

        file_bin = file.read()
        input_format = file.name.rsplit(".", 1)[-1].lower()
        token = secrets.token_urlsafe(16)

        convert_task.delay(file_bin, input_format, output_format, token)
        redis_client.setex(f"conv:{token}", settings.FILE_TTL, token)

        return Response({"result token": token}, status=202)


class ResultsConvertView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request, token):
        try:
            for file in os.listdir(settings.TEMP_DIR):
                if file.startswith(token):
                    path = os.path.join(settings.TEMP_DIR, file)
                    if os.path.isfile(path):
                        mime_type, _ = mimetypes.guess_type(file)
                        return FileResponse(
                            open(path, "rb"),
                            as_attachment=True,
                            filename=file,
                            content_type=mime_type or "application/octet-stream",
                        )

            task_id = redis_client.get(f"conv:{token}")
            if task_id:
                return Response({"result": "Result file not found"}, status=404)

            return Response({"result": "Invalid token or no task found"}, status=404)

        except Exception as e:
            return Response({"result": f"Unexpected error: {str(e)}"}, status=500)

converter/views.py
import os
import time
import secrets
from django.shortcuts import render
from django.http import FileResponse, JsonResponse
from django.urls import reverse
from .utils.cache_func import get_input_choices, get_output_choices
from .utils.redis_ext_client import redis_client
from .forms import ConvertForm, FileForm
from .tasks import convert_task
from celery.result import AsyncResult
from django.conf import settings
from celery_progress.backend import Progress
from .models import FormatType
from django.views.generic.edit import FormView
from django.views.generic import TemplateView
from django.views import View


class GetTargetFormatView(View):
    http_method_names = ["get"]

    def get(self, request):
        input_format = request.GET.get("input_format")
        if not input_format:
            return JsonResponse({"choices": []})
        return JsonResponse({"choices": get_output_choices(input_format)})


class SelectFileView(TemplateView):
    template_name = "converter/convert/select_file.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["format_types"] = FormatType.choices
        return context


class SelectFormatView(FormView):
    template_name = "converter/convert/select_format.html"
    form_class = ConvertForm

    def dispatch(self, request, *args, **kwargs):
        self.category = kwargs["category"]
        return super().dispatch(request, *args, **kwargs)

    def get_initial(self):
        input_choices = get_input_choices(self.category)
        selected_input = (
            self.request.POST.get("input_format")
            or self.request.GET.get("input_format")
            or (input_choices[0][0] if input_choices else None)
        )

        output_choices = get_output_choices(selected_input) if selected_input else []
        selected_output = (
            self.request.POST.get("output_format")
            or self.request.GET.get("output_format")
            or (output_choices[0][0] if output_choices else None)
        )

        self.input_choices = input_choices
        self.output_choices = output_choices

        return {
            "input_format": selected_input,
            "output_format": selected_output,
        }

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields["input_format"].choices = self.input_choices
        form.fields["output_format"].choices = self.output_choices
        return form

    def form_valid(self, form):
        self.cleaned_data = form.cleaned_data
        self.request.session["input_format"] = form.cleaned_data["input_format"]
        self.request.session["output_format"] = form.cleaned_data["output_format"]
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("converter:convert", kwargs=self.cleaned_data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["category"] = self.category
        return context


class ConvertView(FormView):
    form_class = FileForm
    template_name = "converter/convert/file_converter.html"

    def dispatch(self, request, *args, **kwargs):
        self.input_format = kwargs.get("input_format")
        self.output_format = kwargs.get("output_format")
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "input_format": self.input_format,
                "output_format": self.output_format,
                "MAX_FORM_FILE_SIZE": settings.MAX_FORM_FILE_SIZE,
            }
        )
        return context

    def form_valid(self, form):
        file = form.cleaned_data["file"]
        file_bin = file.read()
        token = secrets.token_urlsafe(16)
        task = convert_task.delay(
            file_bin, self.input_format, self.output_format, token
        )
        redis_client.setex(f"conv:{token}", settings.FILE_TTL, task.id)
        progress_url = reverse("converter:convert_progress_info", args=[token])
        return JsonResponse({"token": token, "redirect_url": progress_url})

    def form_invalid(self, form):
        return JsonResponse({"error": form.errors.as_text()}, status=400)


class ProgressbarView(TemplateView):
    template_name = "converter/convert/progress.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["token"] = kwargs.get("token")
        return context


class ConvertProgressView(View):
    http_method_names = ["get"]

    def get(self, request, token, *args, **kwargs):
        try:
            task_id = redis_client.get(f"conv:{token}")
            if not task_id:
                return JsonResponse(
                    {
                        "complete": True,
                        "success": False,
                        "result": "Invalid convert token",
                    }
                )

            task_result = AsyncResult(task_id.decode())
            if task_result.failed():
                return JsonResponse(
                    {
                        "complete": True,
                        "success": False,
                        "result": "Conversion task failed",
                    }
                )

            progress_data = Progress(task_result).get_info()
            return JsonResponse(progress_data)

        except Exception:
            return JsonResponse(
                {
                    "complete": True,
                    "success": False,
                    "result": "Unexpected error",
                }
            )


class DownloadFileView(View):
    http_method_names = ["get"]

    def get(self, request, token):
        temp_path = redis_client.get(f"path:{token}")
        if not temp_path:
            return render(request, "converter/file_not_found.html")

        temp_path = temp_path.decode()

        if (
            not os.path.exists(temp_path)
            or (time.time() - os.path.getmtime(temp_path)) > settings.FILE_TTL
        ):
            return render(request, "converter/file_not_found.html")

        try:
            return FileResponse(
                open(temp_path, "rb"),
                as_attachment=True,
                filename=os.path.basename(temp_path),
            )
        except OSError:
            return render(request, "converter/file_not_found.html")

converter/templates/converter/convert/file_converter.html
{% extends "converter/base.html" %}
{% load static %}

{% block title %}Convert to {{output_format}}{% endblock %}

{% block content %}

<h3 class="convert-heading">Convert your {{ input_format|upper }} file to {{ output_format|upper }}</h3>

<form method="post" enctype="multipart/form-data" class="upload-form" id="upload-form">
  {% csrf_token %}

  {% if form.non_field_errors %}
    <div class="form-errors">
      {% for error in form.non_field_errors %}
        <p class="error">{{ error }}</p>
      {% endfor %}
    </div>
  {% endif %}

  <div class="file-upload-wrapper">
    <label for="file-input" class="drop-zone" id="drop-zone" tabindex="0" role="button" aria-label="Drag and drop file here or click to select">
      <p>Drop your file here or click to select<span class="file-selected-checkmark" aria-hidden="true" style="display:none;">✅</span></p>
    </label>

    <input type="file" name="{{ form.file.name }}" id="file-input" class="file-input"/>

    <div id="file-error" class="error" style="display:none; margin-top: 8px;"></div>
    {% if form.file.errors %}
      <div class="field-errors">
        {% for error in form.file.errors %}
          <p class="error">{{ error }}</p>
        {% endfor %}
      </div>
    {% endif %}
  </div>

  <div class="button-wrapper">
    <button type="submit" class="convert-button">Convert</button>
  </div>
</form>

<script>
    const MAX_SIZE_BYTES = {{ MAX_FORM_FILE_SIZE }};
</script>
<script src="{% static 'converter/js/drag_and_drop.js' %}"></script>

{% endblock %}

converter/templates/converter/convert/progress.html
{% extends "converter/base.html" %}
{% load static %}

{% block title %}Conversion progress{% endblock %}

{% block content %}
<h2 class="convert-heading">Conversion progress</h2>
<div class="progress-checkmark-container">
  <div class="progress-wrapper">
    <div class="progress-bar" id="progress-bar"></div>
  </div>
  <span class="progress-checkmark" aria-hidden="true" style="display: none;">✅</span>
  <span class="progress-error" aria-hidden="true" style="display: none;">❌</span>
</div>

<div class="convert-heading" id="progress-bar-message">Waiting for progress to start...</div>

<div class="convert-heading" id="celery-result"></div>

<div class="button-wrapper" style="text-align:center; margin-top:20px;">
  <button type="button" id="download-btn" class="convert-button" style="display: none;">Download</button>
  <button type="button" id="home-btn" class="convert-button" style="display: none;">Return to the main page</button>
</div>

<div class="button-wrapper" style="text-align:center; margin-top:20px;">
  <div id="home-text-link" class="link-wrapper" style="display: none;">
    <a href="{% url 'home' %}" class="link">Convert More Files</a>
  </div>
</div>

<script src="{% static 'celery_progress/celery_progress.js' %}"></script>
<script>
  const progressUrl = "{% url 'converter:convert_progress' token %}";
  const downloadUrl = "{% url 'converter:download_file' token %}";
  const errorUrl = "{% url 'home' %}";
</script>
<script src="{% static 'converter/js/progressbar.js' %}"></script>

{% endblock %}

converter/templates/converter/convert/select_file.html
{% extends "converter/base.html" %}

{% block title %}Select file type{% endblock %}

{% block content %}

<div class="buttons-container">
{% for low, big in format_types %}
    <a href="{% url "converter:select_format" low %}" class="select-file-btn">Convert {{big}}</a>
{% endfor %}
</div>

{% endblock %}

converter/templates/converter/convert/select_format.html
{% extends "converter/base.html" %}

{% block title %}Select file format{% endblock %}

{% block content %}

<form method="post" id="convert-form" class="convert-form">
    {% csrf_token %}
    <div class="form-row">
        <div class="form-group">
            {{ form.input_format.label_tag }}
            {{ form.input_format }}
        </div>
        <div class="form-group">
            {{ form.output_format.label_tag }}
            {{ form.output_format }}
        </div>
    </div>
    
    <div class="button-wrapper">
        <button type="submit" class="convert-button">Select</button>
    </div>
</form>

{% if '/video/' in request.path %}
  <div class="alert alert-warning" style="margin: 1em auto; text-align: center; max-width: 600px;">
    ⚠️ <strong>Notice:</strong> Video conversion works unstable and may fail or be slow, especially for large files!
  </div>
{% endif %}

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $('#id_input_format').change(function() {
        var inputFormat = $(this).val();
        $.getJSON('{% url "converter:get_target_formats" %}', { input_format: inputFormat }, function(data) {
            let outputSelect = $('#id_output_format');
            outputSelect.empty();
            data.choices.forEach(function(choice) {
                let val = choice[0], label = choice[1];
                outputSelect.append($('<option></option>').attr('value', val).text(label));
            });
        });
    });
</script>

{% endblock %}